<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		$this->call('RegioneTableSeeder');
        $this->command->info('Regiones cargadas!');

        $this->call('ComunaTableSeeder');
        $this->command->info('Comunas cargadas!');
	}

}

class RegioneTableSeeder extends Seeder {

    public function run()
    {
        DB::table('regiones')->delete();

        Regione::create(array('name' => "I. Tarapacá"));
        Regione::create(array('name' => "II. Antofagasta"));
        Regione::create(array('name' => "III. Atacama"));
        Regione::create(array('name' => "IV. Coquimbo"));
        Regione::create(array('name' => "V. Valparaiso"));
        Regione::create(array('name' => "VI. O'Higgins"));
        Regione::create(array('name' => "VII. Maule"));
        Regione::create(array('name' => "VIII. Biobío"));
        Regione::create(array('name' => "IX. La Araucanía"));
        Regione::create(array('name' => "X. Los Lagos"));
        Regione::create(array('name' => "XI. Aysén"));
        Regione::create(array('name' => "XII. Magallanes"));
        Regione::create(array('name' => "RM. Metropolitana"));
        Regione::create(array('name' => "XIV. Los Ríos"));
        Regione::create(array('name' => "XV. Arica y Parinacota"));
    }

}

class ComunaTableSeeder extends Seeder {

    public function run()
    {
        DB::table('comunas')->delete();

        Comuna::create(array('name' => "Aisén", 'region_id' => 11));
        Comuna::create(array('name' => "Algarrobo", 'region_id' => 5));
        Comuna::create(array('name' => "Alhué", 'region_id' => 13));
        Comuna::create(array('name' => "Alto Biobío", 'region_id' => 8));
        Comuna::create(array('name' => "Alto Del Carmen", 'region_id' => 3));
        Comuna::create(array('name' => "Alto Hospicio", 'region_id' => 1));
        Comuna::create(array('name' => "Ancud", 'region_id' => 10));
        Comuna::create(array('name' => "Andacollo", 'region_id' => 4));
        Comuna::create(array('name' => "Angol", 'region_id' => 9));
        Comuna::create(array('name' => "Antártica", 'region_id' => 12));
        Comuna::create(array('name' => "Antofagasta", 'region_id' => 2));
        Comuna::create(array('name' => "Antuco", 'region_id' => 8));
        Comuna::create(array('name' => "Arauco", 'region_id' => 8));
        Comuna::create(array('name' => "Arica", 'region_id' => 15));
        Comuna::create(array('name' => "Buin", 'region_id' => 13));
        Comuna::create(array('name' => "Bulnes", 'region_id' => 8));
        Comuna::create(array('name' => "Cabildo", 'region_id' => 5));
        Comuna::create(array('name' => "Cabo De Hornos", 'region_id' => 12));
        Comuna::create(array('name' => "Cabrero", 'region_id' => 8));
        Comuna::create(array('name' => "Calama", 'region_id' => 2));
        Comuna::create(array('name' => "Calbuco", 'region_id' => 10));
        Comuna::create(array('name' => "Caldera", 'region_id' => 3));
        Comuna::create(array('name' => "Calera", 'region_id' => 5));
        Comuna::create(array('name' => "Calera De Tango", 'region_id' => 13));
        Comuna::create(array('name' => "Calle Larga", 'region_id' => 5));
        Comuna::create(array('name' => "Camarones", 'region_id' => 15));
        Comuna::create(array('name' => "Camiña", 'region_id' => 1));
        Comuna::create(array('name' => "Canela", 'region_id' => 4));
        Comuna::create(array('name' => "Cañete", 'region_id' => 8));
        Comuna::create(array('name' => "Carahue", 'region_id' => 9));
        Comuna::create(array('name' => "Cartagena", 'region_id' => 5));
        Comuna::create(array('name' => "Casablanca", 'region_id' => 5));
        Comuna::create(array('name' => "Castro", 'region_id' => 10));
        Comuna::create(array('name' => "Catemu", 'region_id' => 5));
        Comuna::create(array('name' => "Cauquenes", 'region_id' => 7));
        Comuna::create(array('name' => "Cerrillos", 'region_id' => 13));
        Comuna::create(array('name' => "Cerro Navia", 'region_id' => 13));
        Comuna::create(array('name' => "Chaiten", 'region_id' => 10));
        Comuna::create(array('name' => "Chañaral", 'region_id' => 3));
        Comuna::create(array('name' => "Chanco", 'region_id' => 7));
        Comuna::create(array('name' => "Chépica", 'region_id' => 6));
        Comuna::create(array('name' => "Chiguayante", 'region_id' => 8));
        Comuna::create(array('name' => "Chile Chico", 'region_id' => 11));
        Comuna::create(array('name' => "Chillán", 'region_id' => 8));
        Comuna::create(array('name' => "Chillán Viejo", 'region_id' => 8));
        Comuna::create(array('name' => "Chimbarongo", 'region_id' => 6));
        Comuna::create(array('name' => "Chol Chol", 'region_id' => 9));
        Comuna::create(array('name' => "Chonchi", 'region_id' => 10));
        Comuna::create(array('name' => "Cisnes", 'region_id' => 11));
        Comuna::create(array('name' => "Cobquecura", 'region_id' => 8));
        Comuna::create(array('name' => "Cochamó", 'region_id' => 10));
        Comuna::create(array('name' => "Cochrane", 'region_id' => 11));
        Comuna::create(array('name' => "Codegua", 'region_id' => 6));
        Comuna::create(array('name' => "Coelemu", 'region_id' => 8));
        Comuna::create(array('name' => "Coihaique", 'region_id' => 11));
        Comuna::create(array('name' => "Coihueco", 'region_id' => 8));
        Comuna::create(array('name' => "Coinco", 'region_id' => 6));
        Comuna::create(array('name' => "Colbún", 'region_id' => 7));
        Comuna::create(array('name' => "Colchane", 'region_id' => 1));
        Comuna::create(array('name' => "Colina", 'region_id' => 13));
        Comuna::create(array('name' => "Collipulli", 'region_id' => 9));
        Comuna::create(array('name' => "Coltauco", 'region_id' => 6));
        Comuna::create(array('name' => "Combarbalá", 'region_id' => 4));
        Comuna::create(array('name' => "Concepción", 'region_id' => 8));
        Comuna::create(array('name' => "Conchalí", 'region_id' => 13));
        Comuna::create(array('name' => "Concón", 'region_id' => 5));
        Comuna::create(array('name' => "Constitución", 'region_id' => 7));
        Comuna::create(array('name' => "Contulmo", 'region_id' => 8));
        Comuna::create(array('name' => "Copiapó", 'region_id' => 3));
        Comuna::create(array('name' => "Coquimbo", 'region_id' => 4));
        Comuna::create(array('name' => "Coronel", 'region_id' => 8));
        Comuna::create(array('name' => "Corral", 'region_id' => 14));
        Comuna::create(array('name' => "Cunco", 'region_id' => 9));
        Comuna::create(array('name' => "Curacautín", 'region_id' => 9));
        Comuna::create(array('name' => "Curacaví", 'region_id' => 13));
        Comuna::create(array('name' => "Curaco De Velez", 'region_id' => 10));
        Comuna::create(array('name' => "Curanilahue", 'region_id' => 8));
        Comuna::create(array('name' => "Curarrehue", 'region_id' => 9));
        Comuna::create(array('name' => "Curepto", 'region_id' => 7));
        Comuna::create(array('name' => "Curicó", 'region_id' => 7));
        Comuna::create(array('name' => "Dalcahue", 'region_id' => 10));
        Comuna::create(array('name' => "Diego De Almagro", 'region_id' => 3));
        Comuna::create(array('name' => "Doñihue", 'region_id' => 6));
        Comuna::create(array('name' => "El Bosque", 'region_id' => 13));
        Comuna::create(array('name' => "El Carmen", 'region_id' => 8));
        Comuna::create(array('name' => "El Monte", 'region_id' => 13));
        Comuna::create(array('name' => "El Quisco", 'region_id' => 5));
        Comuna::create(array('name' => "El Tabo", 'region_id' => 5));
        Comuna::create(array('name' => "Empedrado", 'region_id' => 7));
        Comuna::create(array('name' => "Ercilla", 'region_id' => 9));
        Comuna::create(array('name' => "Estación Central", 'region_id' => 13));
        Comuna::create(array('name' => "Florida", 'region_id' => 8));
        Comuna::create(array('name' => "Freire", 'region_id' => 9));
        Comuna::create(array('name' => "Freirina", 'region_id' => 3));
        Comuna::create(array('name' => "Fresia", 'region_id' => 10));
        Comuna::create(array('name' => "Frutillar", 'region_id' => 10));
        Comuna::create(array('name' => "Futaleufú", 'region_id' => 10));
        Comuna::create(array('name' => "Futrono", 'region_id' => 14));
        Comuna::create(array('name' => "Galvarino", 'region_id' => 9));
        Comuna::create(array('name' => "General Lagos", 'region_id' => 15));
        Comuna::create(array('name' => "Gorbea", 'region_id' => 9));
        Comuna::create(array('name' => "Graneros", 'region_id' => 6));
        Comuna::create(array('name' => "Guaitecas", 'region_id' => 11));
        Comuna::create(array('name' => "Hijuelas", 'region_id' => 5));
        Comuna::create(array('name' => "Hualaihué", 'region_id' => 10));
        Comuna::create(array('name' => "Hualañé", 'region_id' => 7));
        Comuna::create(array('name' => "Hualpén", 'region_id' => 8));
        Comuna::create(array('name' => "Hualqui", 'region_id' => 8));
        Comuna::create(array('name' => "Huara", 'region_id' => 1));
        Comuna::create(array('name' => "Huasco", 'region_id' => 3));
        Comuna::create(array('name' => "Huechuraba", 'region_id' => 13));
        Comuna::create(array('name' => "Illapel", 'region_id' => 4));
        Comuna::create(array('name' => "Independencia", 'region_id' => 13));
        Comuna::create(array('name' => "Iquique", 'region_id' => 1));
        Comuna::create(array('name' => "Isla De Maipo", 'region_id' => 13));
        Comuna::create(array('name' => "Isla De Pascua", 'region_id' => 5));
        Comuna::create(array('name' => "Juan Fernandez", 'region_id' => 5));
        Comuna::create(array('name' => "La Cisterna", 'region_id' => 13));
        Comuna::create(array('name' => "La Cruz", 'region_id' => 5));
        Comuna::create(array('name' => "La Estrella", 'region_id' => 6));
        Comuna::create(array('name' => "La Florida", 'region_id' => 13));
        Comuna::create(array('name' => "La Granja", 'region_id' => 13));
        Comuna::create(array('name' => "La Higuera", 'region_id' => 4));
        Comuna::create(array('name' => "La Ligua", 'region_id' => 5));
        Comuna::create(array('name' => "La Pintana", 'region_id' => 13));
        Comuna::create(array('name' => "La Reina", 'region_id' => 13));
        Comuna::create(array('name' => "La Serena", 'region_id' => 4));
        Comuna::create(array('name' => "La Unión", 'region_id' => 14));
        Comuna::create(array('name' => "Lago Ranco", 'region_id' => 14));
        Comuna::create(array('name' => "Lago Verde", 'region_id' => 11));
        Comuna::create(array('name' => "Laguna Blanca", 'region_id' => 12));
        Comuna::create(array('name' => "Laja", 'region_id' => 8));
        Comuna::create(array('name' => "Lampa", 'region_id' => 13));
        Comuna::create(array('name' => "Lanco", 'region_id' => 14));
        Comuna::create(array('name' => "Las Cabras", 'region_id' => 6));
        Comuna::create(array('name' => "Las Condes", 'region_id' => 13));
        Comuna::create(array('name' => "Lautaro", 'region_id' => 9));
        Comuna::create(array('name' => "Lebu", 'region_id' => 8));
        Comuna::create(array('name' => "Licantén", 'region_id' => 7));
        Comuna::create(array('name' => "Limache", 'region_id' => 5));
        Comuna::create(array('name' => "Linares", 'region_id' => 7));
        Comuna::create(array('name' => "Litueche", 'region_id' => 6));
        Comuna::create(array('name' => "Llaillay", 'region_id' => 5));
        Comuna::create(array('name' => "Llanquihue", 'region_id' => 10));
        Comuna::create(array('name' => "Lo Barnechea", 'region_id' => 13));
        Comuna::create(array('name' => "Lo Espejo", 'region_id' => 13));
        Comuna::create(array('name' => "Lo Prado", 'region_id' => 13));
        Comuna::create(array('name' => "Lolol", 'region_id' => 6));
        Comuna::create(array('name' => "Loncoche", 'region_id' => 9));
        Comuna::create(array('name' => "Longaví", 'region_id' => 7));
        Comuna::create(array('name' => "Lonquimay", 'region_id' => 9));
        Comuna::create(array('name' => "Los Alamos", 'region_id' => 8));
        Comuna::create(array('name' => "Los Andes", 'region_id' => 5));
        Comuna::create(array('name' => "Los Ángeles", 'region_id' => 8));
        Comuna::create(array('name' => "Los Lagos", 'region_id' => 14));
        Comuna::create(array('name' => "Los Muermos", 'region_id' => 10));
        Comuna::create(array('name' => "Los Sauces", 'region_id' => 9));
        Comuna::create(array('name' => "Los Vilos", 'region_id' => 4));
        Comuna::create(array('name' => "Lota", 'region_id' => 8));
        Comuna::create(array('name' => "Lumaco", 'region_id' => 9));
        Comuna::create(array('name' => "Machalí", 'region_id' => 6));
        Comuna::create(array('name' => "Macul", 'region_id' => 13));
        Comuna::create(array('name' => "Máfil", 'region_id' => 14));
        Comuna::create(array('name' => "Maipú", 'region_id' => 13));
        Comuna::create(array('name' => "Malloa", 'region_id' => 6));
        Comuna::create(array('name' => "Marchigüe", 'region_id' => 6));
        Comuna::create(array('name' => "María Elena", 'region_id' => 2));
        Comuna::create(array('name' => "María Pinto", 'region_id' => 13));
        Comuna::create(array('name' => "Mariquina", 'region_id' => 14));
        Comuna::create(array('name' => "Maule", 'region_id' => 7));
        Comuna::create(array('name' => "Maullín", 'region_id' => 10));
        Comuna::create(array('name' => "Mejillones", 'region_id' => 2));
        Comuna::create(array('name' => "Melipeuco", 'region_id' => 9));
        Comuna::create(array('name' => "Melipilla", 'region_id' => 13));
        Comuna::create(array('name' => "Molina", 'region_id' => 7));
        Comuna::create(array('name' => "Monte Patria", 'region_id' => 4));
        Comuna::create(array('name' => "Mostazal", 'region_id' => 6));
        Comuna::create(array('name' => "Mulchén", 'region_id' => 8));
        Comuna::create(array('name' => "Nacimiento", 'region_id' => 8));
        Comuna::create(array('name' => "Nancagua", 'region_id' => 6));
        Comuna::create(array('name' => "Natales", 'region_id' => 12));
        Comuna::create(array('name' => "Navidad", 'region_id' => 6));
        Comuna::create(array('name' => "Negrete", 'region_id' => 8));
        Comuna::create(array('name' => "Ninhue", 'region_id' => 8));
        Comuna::create(array('name' => "Ñiquén", 'region_id' => 8));
        Comuna::create(array('name' => "Nogales", 'region_id' => 5));
        Comuna::create(array('name' => "Nueva Imperial", 'region_id' => 9));
        Comuna::create(array('name' => "Ñuñoa", 'region_id' => 13));
        Comuna::create(array('name' => "O'higgins", 'region_id' => 11));
        Comuna::create(array('name' => "Olivar", 'region_id' => 6));
        Comuna::create(array('name' => "Ollagüe", 'region_id' => 2));
        Comuna::create(array('name' => "Olmué", 'region_id' => 5));
        Comuna::create(array('name' => "Osorno", 'region_id' => 10));
        Comuna::create(array('name' => "Ovalle", 'region_id' => 4));
        Comuna::create(array('name' => "Padre Hurtado", 'region_id' => 13));
        Comuna::create(array('name' => "Padre Las Casas", 'region_id' => 9));
        Comuna::create(array('name' => "Paihuano", 'region_id' => 4));
        Comuna::create(array('name' => "Paillaco", 'region_id' => 14));
        Comuna::create(array('name' => "Paine", 'region_id' => 13));
        Comuna::create(array('name' => "Palena", 'region_id' => 10));
        Comuna::create(array('name' => "Palmilla", 'region_id' => 6));
        Comuna::create(array('name' => "Panguipulli", 'region_id' => 14));
        Comuna::create(array('name' => "Panquehue", 'region_id' => 5));
        Comuna::create(array('name' => "Papudo", 'region_id' => 5));
        Comuna::create(array('name' => "Paredones", 'region_id' => 6));
        Comuna::create(array('name' => "Parral", 'region_id' => 7));
        Comuna::create(array('name' => "Pedro Aguirre Cerda", 'region_id' => 13));
        Comuna::create(array('name' => "Pelarco", 'region_id' => 7));
        Comuna::create(array('name' => "Pelluhue", 'region_id' => 7));
        Comuna::create(array('name' => "Pemuco", 'region_id' => 8));
        Comuna::create(array('name' => "Peñaflor", 'region_id' => 13));
        Comuna::create(array('name' => "Peñalolén", 'region_id' => 13));
        Comuna::create(array('name' => "Pencahue", 'region_id' => 7));
        Comuna::create(array('name' => "Penco", 'region_id' => 8));
        Comuna::create(array('name' => "Peralillo", 'region_id' => 6));
        Comuna::create(array('name' => "Perquenco", 'region_id' => 9));
        Comuna::create(array('name' => "Petorca", 'region_id' => 5));
        Comuna::create(array('name' => "Peumo", 'region_id' => 6));
        Comuna::create(array('name' => "Pica", 'region_id' => 1));
        Comuna::create(array('name' => "Pichidegua", 'region_id' => 6));
        Comuna::create(array('name' => "Pichilemu", 'region_id' => 6));
        Comuna::create(array('name' => "Pinto", 'region_id' => 8));
        Comuna::create(array('name' => "Pirque", 'region_id' => 13));
        Comuna::create(array('name' => "Pitrufquén", 'region_id' => 9));
        Comuna::create(array('name' => "Placilla", 'region_id' => 6));
        Comuna::create(array('name' => "Portezuelo", 'region_id' => 8));
        Comuna::create(array('name' => "Porvenir", 'region_id' => 12));
        Comuna::create(array('name' => "Pozo Almonte", 'region_id' => 1));
        Comuna::create(array('name' => "Primavera", 'region_id' => 12));
        Comuna::create(array('name' => "Providencia", 'region_id' => 13));
        Comuna::create(array('name' => "Puchuncaví", 'region_id' => 5));
        Comuna::create(array('name' => "Pucón", 'region_id' => 9));
        Comuna::create(array('name' => "Pudahuel", 'region_id' => 13));
        Comuna::create(array('name' => "Puente Alto", 'region_id' => 13));
        Comuna::create(array('name' => "Puerto Montt", 'region_id' => 10));
        Comuna::create(array('name' => "Puerto Octay", 'region_id' => 10));
        Comuna::create(array('name' => "Puerto Varas", 'region_id' => 10));
        Comuna::create(array('name' => "Pumanque", 'region_id' => 6));
        Comuna::create(array('name' => "Punitaqui", 'region_id' => 4));
        Comuna::create(array('name' => "Punta Arenas", 'region_id' => 12));
        Comuna::create(array('name' => "Puqueldón", 'region_id' => 10));
        Comuna::create(array('name' => "Purén", 'region_id' => 9));
        Comuna::create(array('name' => "Purranque", 'region_id' => 10));
        Comuna::create(array('name' => "Putaendo", 'region_id' => 5));
        Comuna::create(array('name' => "Putre", 'region_id' => 15));
        Comuna::create(array('name' => "Puyehue", 'region_id' => 10));
        Comuna::create(array('name' => "Queilén", 'region_id' => 10));
        Comuna::create(array('name' => "Quellón", 'region_id' => 10));
        Comuna::create(array('name' => "Quemchi", 'region_id' => 10));
        Comuna::create(array('name' => "Quilaco", 'region_id' => 8));
        Comuna::create(array('name' => "Quilicura", 'region_id' => 13));
        Comuna::create(array('name' => "Quilleco", 'region_id' => 8));
        Comuna::create(array('name' => "Quillón", 'region_id' => 8));
        Comuna::create(array('name' => "Quillota", 'region_id' => 5));
        Comuna::create(array('name' => "Quilpué", 'region_id' => 5));
        Comuna::create(array('name' => "Quinchao", 'region_id' => 10));
        Comuna::create(array('name' => "Quinta De Tilcoco", 'region_id' => 6));
        Comuna::create(array('name' => "Quinta Normal", 'region_id' => 13));
        Comuna::create(array('name' => "Quintero", 'region_id' => 5));
        Comuna::create(array('name' => "Quirihue", 'region_id' => 8));
        Comuna::create(array('name' => "Rancagua", 'region_id' => 6));
        Comuna::create(array('name' => "Ránquil", 'region_id' => 8));
        Comuna::create(array('name' => "Rauco", 'region_id' => 7));
        Comuna::create(array('name' => "Recoleta", 'region_id' => 13));
        Comuna::create(array('name' => "Renaico", 'region_id' => 9));
        Comuna::create(array('name' => "Renca", 'region_id' => 13));
        Comuna::create(array('name' => "Rengo", 'region_id' => 6));
        Comuna::create(array('name' => "Requínoa", 'region_id' => 6));
        Comuna::create(array('name' => "Retiro", 'region_id' => 7));
        Comuna::create(array('name' => "Rinconada", 'region_id' => 5));
        Comuna::create(array('name' => "Río Bueno", 'region_id' => 14));
        Comuna::create(array('name' => "Río Claro", 'region_id' => 7));
        Comuna::create(array('name' => "Río Hurtado", 'region_id' => 4));
        Comuna::create(array('name' => "Río Ibañez", 'region_id' => 11));
        Comuna::create(array('name' => "Río Negro", 'region_id' => 10));
        Comuna::create(array('name' => "Río Verde", 'region_id' => 12));
        Comuna::create(array('name' => "Romeral", 'region_id' => 7));
        Comuna::create(array('name' => "Saavedra", 'region_id' => 9));
        Comuna::create(array('name' => "Sagrada Familia", 'region_id' => 7));
        Comuna::create(array('name' => "Salamanca", 'region_id' => 4));
        Comuna::create(array('name' => "San Antonio", 'region_id' => 5));
        Comuna::create(array('name' => "San Bernardo", 'region_id' => 13));
        Comuna::create(array('name' => "San Carlos", 'region_id' => 8));
        Comuna::create(array('name' => "San Clemente", 'region_id' => 7));
        Comuna::create(array('name' => "San Esteban", 'region_id' => 13));
        Comuna::create(array('name' => "San Fabián", 'region_id' => 8));
        Comuna::create(array('name' => "San Felipe", 'region_id' => 5));
        Comuna::create(array('name' => "San Fernando", 'region_id' => 6));
        Comuna::create(array('name' => "San Gregorio", 'region_id' => 12));
        Comuna::create(array('name' => "San Ignacio", 'region_id' => 8));
        Comuna::create(array('name' => "San Javier", 'region_id' => 7));
        Comuna::create(array('name' => "San Joaquín", 'region_id' => 13));
        Comuna::create(array('name' => "San José De Maipo", 'region_id' => 13));
        Comuna::create(array('name' => "San Juan De La Costa", 'region_id' => 10));
        Comuna::create(array('name' => "San Miguel", 'region_id' => 13));
        Comuna::create(array('name' => "San Nicolás", 'region_id' => 8));
        Comuna::create(array('name' => "San Pablo", 'region_id' => 10));
        Comuna::create(array('name' => "San Pedro", 'region_id' => 13));
        Comuna::create(array('name' => "San Pedro De Atacama", 'region_id' => 2));
        Comuna::create(array('name' => "San Pedro De La Paz", 'region_id' => 8));
        Comuna::create(array('name' => "San Rafael", 'region_id' => 7));
        Comuna::create(array('name' => "San Ramón", 'region_id' => 13));
        Comuna::create(array('name' => "San Rosendo", 'region_id' => 8));
        Comuna::create(array('name' => "San Vicente", 'region_id' => 6));
        Comuna::create(array('name' => "Santa Bárbara", 'region_id' => 8));
        Comuna::create(array('name' => "Santa Cruz", 'region_id' => 6));
        Comuna::create(array('name' => "Santa Juana", 'region_id' => 8));
        Comuna::create(array('name' => "Santa María", 'region_id' => 5));
        Comuna::create(array('name' => "Santiago", 'region_id' => 13));
        Comuna::create(array('name' => "Santo Domingo", 'region_id' => 5));
        Comuna::create(array('name' => "Sierra Gorda", 'region_id' => 2));
        Comuna::create(array('name' => "Talagante", 'region_id' => 13));
        Comuna::create(array('name' => "Talca", 'region_id' => 7));
        Comuna::create(array('name' => "Talcahuano", 'region_id' => 8));
        Comuna::create(array('name' => "Taltal", 'region_id' => 2));
        Comuna::create(array('name' => "Temuco", 'region_id' => 9));
        Comuna::create(array('name' => "Teno", 'region_id' => 7));
        Comuna::create(array('name' => "Teodoro Schmidt", 'region_id' => 9));
        Comuna::create(array('name' => "Tierra Amarilla", 'region_id' => 3));
        Comuna::create(array('name' => "Tiltil", 'region_id' => 13));
        Comuna::create(array('name' => "Timaukel", 'region_id' => 12));
        Comuna::create(array('name' => "Tirúa", 'region_id' => 8));
        Comuna::create(array('name' => "Tocopilla", 'region_id' => 2));
        Comuna::create(array('name' => "Toltén", 'region_id' => 9));
        Comuna::create(array('name' => "Tomé", 'region_id' => 8));
        Comuna::create(array('name' => "Torres Del Paine", 'region_id' => 12));
        Comuna::create(array('name' => "Tortel", 'region_id' => 11));
        Comuna::create(array('name' => "Traiguén", 'region_id' => 9));
        Comuna::create(array('name' => "Treguaco", 'region_id' => 8));
        Comuna::create(array('name' => "Tucapel", 'region_id' => 8));
        Comuna::create(array('name' => "Valdivia", 'region_id' => 14));
        Comuna::create(array('name' => "Vallenar", 'region_id' => 3));
        Comuna::create(array('name' => "Valparaíso", 'region_id' => 5));
        Comuna::create(array('name' => "Vichuquén", 'region_id' => 7));
        Comuna::create(array('name' => "Victoria", 'region_id' => 9));
        Comuna::create(array('name' => "Vicuña", 'region_id' => 4));
        Comuna::create(array('name' => "Vilcún", 'region_id' => 9));
        Comuna::create(array('name' => "Villa Alegre", 'region_id' => 7));
        Comuna::create(array('name' => "Villa Alemana", 'region_id' => 5));
        Comuna::create(array('name' => "Villarrica", 'region_id' => 9));
        Comuna::create(array('name' => "Viña Del Mar", 'region_id' => 5));
        Comuna::create(array('name' => "Vitacura", 'region_id' => 13));
        Comuna::create(array('name' => "Yerbas Buenas", 'region_id' => 7));
        Comuna::create(array('name' => "Yumbel", 'region_id' => 8));
        Comuna::create(array('name' => "Yungay", 'region_id' => 8));
        Comuna::create(array('name' => "Zapallar", 'region_id' => 5));
    }

}